### ISSUE TITLE
May I merge the tryf# website tutorials into the .NET tutorials?

### ISSUE THREAD

**Issue by rogersachan** [dotnet/training-tutorials#155]
I have made a copy of most of the lessons of the tryfsharp.org/Learn site at [rogersachan/tryfsharpwiki](https://github.com/rogersachan/tryfsharpwiki/wiki) in the wiki section. Could this possibly be merged in the near future?

**Comment by ardalis** [comment]
Hi @rogersachan,

Yes, that would be great. Can you fork this repo and submit a PR with the F# content arranged in its own folder, like csharp is now?

**Comment by rogersachan** [comment]
I'll have that tomorrow at best. I haven't been on at all lately due to a ATT Uverse installation gone wrong.

Thanks,
Roger

**Comment by ardalis** [comment]
Any update?

**Comment by rogersachan** [comment]
@ardalis I'm working on it right now. The tutorials occasionally used the built in REPL (which we lost a short while before preview2 of the .NET Core SDK) and I have gone back and scrubbed most of that out. I have credited all articles to Microsoft Research due to the site not giving any credits to anyone.

I'll most likely have it done by the end of the day.

Thanks,
Roger

**Comment by rogersachan** [comment]
The try f# site loads more complete code snippets than the one given.

e.g.

Seen:
```fsharp
Chart.Combine([ Chart.Line [(2, 15); (1, 10)]
                Chart.Line [(2, 10); (1, 15)] ])
```

In IDE:
```fsharp
open Samples.Charting.DojoChart

Chart.Combine([ Chart.Line [(2, 15); (1, 10)]
                Chart.Line [(2, 10); (1, 15)] ])
```

How do I replicate this? I've made a separate repo for the files given by pressing the load button.
