### ISSUE TITLE
middleware-basic.md Sample program gives a compiling error when testing.

### ISSUE THREAD

**Issue by Pastrie** [dotnet/training-tutorials#198]
While working my way through the ASP.NET tutorials I found an issue with one of the code snippets. At least I think it's an issue. I'm new to C# and especially ASP.NET.

Anyway while researching what might cause this error I came across this StackOverflow post. [howto-count-the-items-from-a-ienumerablet-without-iterating](https://stackoverflow.com/questions/168901/howto-count-the-items-from-a-ienumerablet-without-iterating)

I resolved the compiling error by changing the interface to IList rather than IEnumerable.
![middleware-basic md](https://user-images.githubusercontent.com/6128840/34321801-39fd4d10-e7e5-11e7-9e14-e5da4aef3307.PNG)

**Comment by svick** [comment]
You are right that this is an issue with the code. Using `IList<T>` is one way to fix it, another (one which I would prefer) would be to use `IReadOnlyCollection<T>` instead. Do you want to submit a Pull Request with that change?

**Comment by ardalis** [comment]
The other way to solve this would be to simply use LINQ and replace `.Count` with `.Count()`.
