### ISSUE TITLE
Serving Static Files

### ISSUE THREAD

**Issue by ardalis** [dotnet/training-tutorials#50]
ASPNET > Getting Started

Show how to add support for serving static files.

Add some static files. Maybe a favicon and/or some CSS that will be used by responses. Maybe an index.html.

**Comment by MisterJames** [comment]
I'll take this one.

**Comment by ardalis** [comment]
Build off of the sample I just checked in here: /content/asp.net/getting-started/samples/quotes/ (currently in PR).

**Comment by ardalis** [comment]
Alternately, if you want to just jump ahead to MVC, I'll finish out the non-MVC stuff. You would start with issue #59 at that point.
