### ISSUE TITLE
Returning Data or Views from Controllers

### ISSUE THREAD

**Issue by ardalis** [dotnet/training-tutorials#61]
ASPNET > Getting Started

Expand on previous article regarding Controller helpers for creating views. Talk about how to refer to views (empty string, by name, by filename).

For Web API, talk about returning simple types, but then show that returning an IActionResult is better. See https://github.com/aspnet/Docs/pull/1327 (which will be on docs.asp.net soon) for reference.

**Comment by MisterJames** [comment]
Closed by #162
