### ISSUE TITLE
Sending Data to Controllers

### ISSUE THREAD

**Issue by ardalis** [dotnet/training-tutorials#62]
ASPNET > Getting Started

Getting data to _Controllers_ would be things like DI and configuration. Reference this and mention that DI is coming in next article.

More specifically, this lesson is about getting data to _actions_ within a controller, and as such should focus primarily on Model Binding. Discuss how the action can get access (either through its model bound parameters, or otherwise) to request data from any of these:
- Querystring
- POST data
- URL/routing tokens (e.g. /{id?} )

Also talk about things like [FromBody] attribute and when it's required. Should be scenario-based, not just a repeat of the docs on model binding, though.

**Comment by MisterJames** [comment]
Closed by #163
