### ISSUE TITLE
Working with ASP.NET Core MVC Views

### ISSUE THREAD

**Issue by ardalis** [dotnet/training-tutorials#65]
ASPNET > Getting Started

Enhance the application that's being built by leveraging some view features:
- ViewStart
- ViewImports
- Layout
- Partials
- Passing viewmodels into views (@model attribute in view)

No need to go into huge depth with these. Refer to docs for more. 
https://docs.asp.net/en/latest/mvc/views/index.html

**Comment by MisterJames** [comment]
Closed by #187
