### ISSUE TITLE
Understanding ASP.NET Core MVC Filters

### ISSUE THREAD

**Issue by ardalis** [dotnet/training-tutorials#66]
ASPNET > Getting Started

Review some controller code we've built so far. Identify some duplicate logic.
- Introduce Filters
- Show how to use a built-in filter to reduce some duplication / perform some work (if we can)
- Show how to create and use a custom filter

Reference:
https://docs.asp.net/en/latest/mvc/controllers/filters.html
Steve has a Filters article that will be in August MSDN he can share

**Comment by ardalis** [comment]
@MisterJames let me know when you get to this one and if you want it you can have it.

**Comment by MisterJames** [comment]
I'm on this one now.
